### ISSUE TITLE
Remove Guzzle

### ISSUE THREAD

**Issue by michaelcurry** [naughtonium/laravel-dark-sky#1]
Guzzle is one of those packages that introduces breaking changes between old and new versions...  Unfortunately, I am unable to utilize the Guzzle version on this package (dependency issues).  Would you be up to using `curl` in this package to remove the Guzzle dependency?

I may have a bit of time to do this if you do not.  Please let me know :)

**Comment by Holiehandgrenade** [comment]
Hi Michael. Ironically I had originally written it in vanilla php and then
decided to clean it up with guzzle.  I'll see what I can do today, and let
you know!
