### ISSUE TITLE
Class DarkSky not found? 

### ISSUE THREAD

**Issue by rannieo** [naughtonium/laravel-dark-sky#5]
Thank your for your wonderful library, but i tried to used but i had an error that said `Class DarkSky not found` I already follow the documentation. Thanks.

**Comment by Holiehandgrenade** [comment]
Hi there. Are you using version 5.6?

**Comment by Holiehandgrenade** [comment]
Hi there, I will be looking into this and will get back to you soon. Thank you for the support

**Comment by Holiehandgrenade** [comment]
@einnar82 I've just tested it on a new laravel project v 5.6.12 and it is working. Which Laravel version are you using?

Additionally, did you make sure to register the Provider and Alias in the respective arrays found in config/app.php?

**Comment by rannieo** [comment]
i am using the same project. i also followed the steps.

**Comment by Holiehandgrenade** [comment]
@einnar82 Hmm. Well off the top of my head I am not sure beyond that. If you have a repository I can view, I'd be happy to look through and see if there's something I can do.

**Comment by rannieo** [comment]
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DarkSky;
class WeatherNotificationsController extends Controller
{
  public function getWeatherUpdate()
	{
		\DarkSky::location(14.7728, 120.9704)->get();
	}
}`

**Comment by Holiehandgrenade** [comment]
@einnar82 Try without the leading backslash. 
DarkSky::location(14.7728, 120.9704)->get();
